### ISSUE TITLE
Error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kkharji** [heavenshell/vim-gql#2]
Hello, thank you for this awsome utility.

I'm trying to test querying from https://api.spacex.land/graphql/. However, when I execute :
`'<,'>Gql -server https://api.spacex.land/graphql`
```
query { launchesPast { 
  mission_name 
  } 
}


```
I get the following error: I tried looking into docs but no mention of variable or something I didn't set that my resulted in this issue 

```
Traceback (most recent call last):
  File "/home/a/.cache/nvim/dein/repos/github.com/heavenshell/vim-gql/scripts/format.py", line 17, in <module>
    main(lines)
  File "/home/a/.cache/nvim/dein/repos/github.com/heavenshell/vim-gql/scripts/format.py", line 7, in main
    json.loads(lines),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by heavenshell** [comment]
@tamibam 
Thank you for trying this and reporting issue.

Works fine at Vim8.0.1633

I tried https://api.spacex.land/graphql/ 's sample
```
{
  launchesPast(limit: 10) {
    mission_name
    launch_date_local
    launch_site {
      site_name_long
    }
    links {
      article_link
      video_link
    }
    rocket {
      rocket_name
      first_stage {
        cores {
          flight
          core {
            reuse_count
            status
          }
        }
      }
      second_stage {
        payloads {
          payload_type
          payload_mass_kg
          payload_mass_lbs
        }
      }
    }
    ships {
      name
      home_port
      image
    }
  }
}
```

![Kapture 2020-06-06 at 21 16 01](https://user-images.githubusercontent.com/56591/83943966-1493f880-a83b-11ea-9e5d-e9c3ff40381a.gif)

Can you show me your GraphQL file?

**Comment by kkharji** [comment]
Hay, Thank you for checking the issue. I've actualy test it out on an empty buffer, should I use .graphql?

I use nvim 0.5 nightly.

EDIT: tested it with graphql file, still same issue. perhaps its a nvim thing?

**Comment by heavenshell** [comment]
Thanks for response.

humm, maybe Neovim thing, but error message says
```
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
something wrong with response value.

Can you capture response value?

- vim autoload/gql.vim
  - open gql.vim 
- insert debug print at line 83
- `echomsg string(res.content)`
- execute gql
- after error raised, type `:message`
- screencapture Vim

<img width="650" alt="スクリーンショット 2020-06-07 12 20 17" src="https://user-images.githubusercontent.com/56591/83959570-53689380-a8b9-11ea-8219-a0c5a0fab97f.png">

**Comment by kkharji** [comment]
![image](https://user-images.githubusercontent.com/65782666/83962857-b94d1f00-a8a9-11ea-91ee-2cc79192ec9a.png)

This is what I got in messages after adding echomsg

**Comment by heavenshell** [comment]
@tamibam 
Thanks! 
Ah~. Maybe you need to install https://github.com/mattn/webapi-vim
Sorry I didn't mention about webapi-vim

Please try install webapi-vim

**Comment by kkharji** [comment]
YES, that solved the issue, thank you very much for working with me to fix it. please do included it in readme.
